services:
  worker:
    image: arxseni/cic-main:worker-latest
    environment:
      - MOCK_MODE=False
      - MONITOR_URL=http://monitor:5001
      - WORKER_ID=worker_1
    env_file:
      - .env
    ports:
      - "5002:5002"
    depends_on:
      - monitor

  monitor:
    image: arxseni/cic-main:monitor-latest
    ports:
      - "5001:5001"
    environment:
      - COST_LIMIT=100.0
      - COST_PER_REQUEST=0.01