services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MOCK_MODE=False
      - MONITOR_URL=http://monitor:5001
      - WORKER_ID=worker_1
    env_file:
      - .env
    ports:
      - "5002:5002"
    depends_on:
      - monitor

  monitor:
    build:
      context: ./monitor
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - COST_LIMIT=100.0
      - COST_PER_REQUEST=0.01