apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor
        image: arxseni/cic-main:monitor-latest
        ports:
        - containerPort: 5001
        env:
        - name: COST_LIMIT
          value: "100.0"
        - name: COST_PER_REQUEST
          value: "0.01"